# Generated by Django 2.2.14 on 2020-07-09 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/jobs/')),
                ('summary', models.CharField(max_length=200)),
            ],
        ),
    ]
